import os
import re
import json
from datetime import datetime
import streamlit as st
import pandas as pd
import altair as alt

from graph.graph import run_goal_creation, run_goal_decomposition
from services.llm import MODEL
from services.storage import save_plan
from services.break_agent import auto_mindfulness_reminder
from graph.break_graph import run_break_workflow
from graph.break_graph import run_llm_break_workflow
from graph.schemas import CheckIn
#profilepersonalisation and Workload adaptation
from graph.graph import run_personalized_goal, run_workload_adaptation

from graph.graph import run_morning_checkin
from services.session import init_session, start_session, stop_session, next_step, get_state
from services.langgraph_agent import run_mentor_cycle

try:
    from services.storage import save_profile, load_profile
except Exception:
    save_profile = None
    load_profile = lambda *args, **kwargs: None


# --- UI helper: provenance + confidence chip -----------------
def render_confidence(provenance: str | None, confidence: float | None, key: str):
    provenance = (provenance or "unknown").lower()
    label = {"llm": "Generated by LLM", "fallback": "Generated by Fallback"}.get(provenance, "Source: Unknown")
    # pick a default confidence if not provided
    conf = confidence if confidence is not None else (0.85 if provenance == "llm" else 0.55 if provenance == "fallback" else 0.65)
    pct = int(max(0, min(100, round(conf * 100))))
    st.markdown(
        f"""
        <div style="display:flex;align-items:center;gap:.5rem;margin:.5rem 0 .25rem 0;">
            <span style="font-size:.85rem;padding:.15rem .5rem;border-radius:999px;background:#eef; color:#223;">
                {label}
            </span>
            <span style="font-size:.8rem;color:#666;">Confidence: {pct}%</span>
        </div>
        """,
        unsafe_allow_html=True,
    )
    st.progress(pct, text="")  # small visual bar


# ──────────────────────────────────────────────────────────────────────────────
# Page Setup
# ──────────────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Corporate Mindfulness Mentor",
    page_icon="🧘",
    layout="centered",
)

# Readable card style for plan summary (works in light/dark)
st.markdown("""
<style>
.plan-card {
  padding: 18px 20px;
  border-radius: 12px;
  border: 1px solid rgba(148,163,184,.35); /* slate-400-ish */
  background: rgba(2, 6, 23, 0.35);        /* subtle dark overlay */
  color: #e5e7eb;                           /* slate-200 text */
  line-height: 1.7;
}
@media (prefers-color-scheme: light) {
  .plan-card {
    background: #f8fafc;                    /* light card */
    color: #0f172a;                         /* slate-900 */
    border-color: rgba(15,23,42,.15);
  }
}
.plan-card p { margin: 0 0 .7rem 0; }
</style>
""", unsafe_allow_html=True)



# ──────────────────────────────────────────────────────────────
# Sidebar settings for mindful break notifications
# ──────────────────────────────────────────────────────────────
with st.sidebar:
    st.header("🧘 Mindful Break Settings")
    enable_auto_breaks = st.checkbox("Enable automatic reminders", value=True, key="auto_breaks_toggle")
    play_sound = st.checkbox("🔔 Sound alert", value=True, key="sound_alert_toggle")



# ──────────────────────────────────────────────────────────────────────────────
# Session State Init
# ──────────────────────────────────────────────────────────────────────────────
def init_session_state():
    if "result" not in st.session_state:
        st.session_state["result"] = None
    if "goal_history" not in st.session_state:
        st.session_state["goal_history"] = []
    if "saved_plans" not in st.session_state:
        st.session_state["saved_plans"] = {}
    if "current_goal_id" not in st.session_state:
        st.session_state["current_goal_id"] = None
    if "last_input" not in st.session_state:
        st.session_state["last_input"] = None
    if "decomposition" not in st.session_state:
        st.session_state["decomposition"] = None

init_session_state()

# ──────────────────────────────────────────────────────────────────────────────
# Persistence Helpers
# ──────────────────────────────────────────────────────────────────────────────
def save_plan_to_history(goal_name: str, duration_type: str, result):
    """Save a plan to the session history and return its ID."""
    goal_id = f"goal_{len(st.session_state['goal_history']) + 1}"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    plan_data = {
        "id": goal_id,
        "name": goal_name,
        "duration": duration_type,
        "timestamp": timestamp,
        "activities": result.suggested_activities,
        "summary": result.ai_summary,
    }

    st.session_state["goal_history"].append(plan_data)
    st.session_state["saved_plans"][goal_id] = plan_data
    st.session_state["current_goal_id"] = goal_id
    return goal_id

def load_plan_from_history(goal_id: str):
    """Load a plan from session history."""
    if goal_id in st.session_state["saved_plans"]:
        plan = st.session_state["saved_plans"][goal_id]
        from graph.schemas import PlanResponse
        return PlanResponse(
            goal=plan["name"],
            suggested_activities=plan["activities"],
            ai_summary=plan["summary"],
        )
    return None

def export_all_plans_json():
    """Export all saved plans as JSON."""
    return json.dumps(st.session_state["saved_plans"], indent=2)

def export_plan_markdown(plan_data):
    """Export a single plan to Markdown."""
    md = f"""# Mindfulness Plan: {plan_data['name']}

**Duration:** {plan_data['duration']}  
**Created:** {plan_data['timestamp']}

## 🎯 Activities

"""
    for i, activity in enumerate(plan_data["activities"], 1):
        md += f"{i}. {activity}\n"

    md += f"\n## 📝 Summary\n\n{plan_data['summary']}\n"
    return md

# ──────────────────────────────────────────────────────────────────────────────
# UI: Title & Sidebar (CLEANED UP)
# ──────────────────────────────────────────────────────────────────────────────
st.title("🧘‍♀️ Corporate Mindfulness Mentor")
st.subheader("Goal Creation & Personalized Plan")

with st.sidebar:
    # Only show essential info to users
    st.markdown("### 📊 Your Progress")
    total_plans = len(st.session_state["goal_history"])
    st.metric("Total Plans Created", total_plans)
    
    # Only show API status if there's an issue
    if not os.getenv("OPENAI_API_KEY"):
        st.error("⚠️ API Key Missing")
        st.caption("Please add OPENAI_API_KEY to your .env file")
    
    st.markdown("---")

    # Goal History (user-friendly)
    if st.session_state["goal_history"]:
        st.markdown("### 📚 Previous Goals")
        
        for plan in reversed(st.session_state["goal_history"][-10:]):
            with st.expander(f"📋 {plan['name'][:35]}...", expanded=False):
                st.caption(f"Created: {plan['timestamp']}")
                st.caption(f"Duration: {plan['duration'].title()}")
                
                col1, col2 = st.columns(2)
                with col1:
                    if st.button("📖 Load", key=f"load_{plan['id']}", use_container_width=True):
                        loaded_plan = load_plan_from_history(plan["id"])
                        if loaded_plan:
                            st.session_state["result"] = loaded_plan
                            st.session_state["current_goal_id"] = plan["id"]
                            st.session_state["decomposition"] = None
                            st.rerun()

                with col2:
                    md_content = export_plan_markdown(plan)
                    st.download_button(
                        "💾 Save",
                        data=md_content,
                        file_name=f"{plan['name'][:20].replace(' ', '_')}.md",
                        mime="text/markdown",
                        key=f"dl_{plan['id']}",
                        use_container_width=True,
                    )

        st.markdown("---")
        
        # Export all option
        col1, col2 = st.columns([2, 1])
        with col1:
            st.caption("Export all your plans")
        with col2:
            json_data = export_all_plans_json()
            st.download_button(
                "📦 Export",
                data=json_data,
                file_name=f"all_plans_{datetime.now().strftime('%Y%m%d')}.json",
                mime="application/json",
                use_container_width=True,
            )

    st.markdown("---")
    
    # Reset button
    if st.button("🔄 Start Fresh", help="Clear all saved plans", use_container_width=True):
        if st.session_state["goal_history"]:
            # Show confirmation
            st.session_state.clear()
            st.rerun()

# ──────────────────────────────────────────────────────────────────────────────
# Main Form
# ──────────────────────────────────────────────────────────────────────────────
with st.form("goal_form", clear_on_submit=False):
    goal_name = st.text_input(
        "What's your mindfulness goal?",
        value="",
        placeholder="e.g., Reduce daily stress, Improve focus, Manage anxiety",
        help="Be specific about what you want to achieve",
    )

    DURATION_CHOICES = ["— select frequency —", "daily", "weekly", "monthly"]
    duration_choice = st.selectbox(
        "How often will you practice?",
        options=DURATION_CHOICES,
        index=0,
        help="Choose how frequently you want to practice these activities",
    )
    duration_type = None if duration_choice == DURATION_CHOICES[0] else duration_choice

    description = st.text_area(
        "Additional context (optional)",
        value="",
        placeholder="Share details about your schedule, work environment, or specific challenges...",
        help="More context helps us create a better personalized plan",
        height=100,
    )

    col_btn1, col_btn2 = st.columns(2)
    with col_btn1:
        submitted = st.form_submit_button("✨ Generate My Plan", use_container_width=True, type="primary")
    with col_btn2:
        decompose_request = st.form_submit_button("📅 Break Into Steps", use_container_width=True)

# ──────────────────────────────────────────────────────────────────────────────
# Handle Form Actions
# ──────────────────────────────────────────────────────────────────────────────
if submitted:
    goal_ok = bool(goal_name.strip())
    duration_ok = duration_type is not None

    if not goal_ok or not duration_ok:
        if not goal_ok:
            st.warning("💭 Please tell us your mindfulness goal")
        if not duration_ok:
            st.warning("📅 Please select how often you'll practice")
    else:
        try:
            with st.spinner("✨ Creating your personalized mindfulness plan..."):
                result = run_goal_creation(
                    goal_name.strip(),
                    duration_type,
                    description.strip(),
                )

            st.session_state["result"] = result

        
            st.session_state["last_input"] = {
                "goal_name": goal_name.strip(),
                "duration_type": duration_type,
                "description": description.strip(),
            }
            st.session_state["decomposition"] = None

            save_plan_to_history(goal_name.strip(), duration_type, result)

            try:
                save_plan(result.model_dump())
            except Exception:
                pass  # Silent fail for storage

            st.success("✅ Your personalized plan is ready!")
            st.balloons()

        except Exception as e:
            st.error("😔 Oops! Something went wrong creating your plan.")
            st.caption(f"Error details: {str(e)}")
            st.info("💡 Try again or contact support if the problem persists.")

if decompose_request:
    if st.session_state.get("result") is None:
        st.info("💡 First, generate a plan, then you can break it into weekly steps!")
    else:
        li = st.session_state.get("last_input") or {}
        try:
              li = st.session_state.get("last_input") or {}
              cadence = li.get("duration_type", "weekly")  # "daily" | "weekly" | "monthly"
              with st.spinner(f"🔄 Breaking your goal into {cadence} milestones..."):
                  dec = run_goal_decomposition(
                      goal_name=li.get("goal_name", st.session_state["result"].goal),
                      duration_type=cadence,
                      description=li.get("description", ""),
                  )
              st.session_state["decomposition"] = dec
              st.success(f"✅ Your {cadence.title()} roadmap is ready!")
        except Exception as e:
            st.error("😔 Couldn't create weekly breakdown.")
            st.caption(f"Error: {str(e)}")
      

# ──────────────────────────────────────────────────────────────────────────────
# Display Decomposition (Milestones)
# ──────────────────────────────────────────────────────────────────────────────
dec = st.session_state.get("decomposition")
if dec:
    st.markdown("---")
    title_cadence = (dec.duration_type or "weekly").title()
    st.markdown(f"## 📅 Your {title_cadence} Roadmap")
    st.caption("Here's how to achieve your goal step by step")
    
    for idx, sg in enumerate(dec.subgoals, start=1):
        title = getattr(sg, "title", "This Week's Focus")
        timeframe = getattr(sg, "timeframe", f"Week {idx}")
        activities = getattr(sg, "activities", []) or []
        
        with st.expander(f"**{timeframe}: {title}**", expanded=(idx == 1)):
            st.markdown("**Activities for this period:**")
            for i, activity in enumerate(activities, 1):
                st.markdown(f"{i}. {activity}")
    
    if hasattr(dec, 'ai_summary') and dec.ai_summary:
        st.markdown("---")
        st.markdown("### 🌱 Why This Sequence?")
        st.info(dec.ai_summary)

# ──────────────────────────────────────────────────────────────────────────────
# Display Main Plan (Activities & Summary)
# ──────────────────────────────────────────────────────────────────────────────
result = st.session_state.get("result")
if result:
    st.markdown("---")

    # Header
    st.markdown(f"## 🎯 Your Goal: {result.goal}")
    
    current_id = st.session_state.get("current_goal_id")
    if current_id and current_id in st.session_state["saved_plans"]:
        st.caption(f"Saved as: {current_id}")

    # Activities
    st.markdown("### 📋 Your Daily Practices")
    st.caption("Check off activities as you complete them")
    
    for i, act in enumerate(result.suggested_activities, start=1):
        checkbox_key = f"activity_{current_id}_{i}" if current_id else f"activity_temp_{i}"
        st.checkbox(f"**{i}.** {act}", key=checkbox_key)

    # Summary
    st.markdown("---")
    st.markdown("### 💡 About Your Plan")
    clean_summary = re.sub(r"#+\s*", "", result.ai_summary or "").strip()
    html_summary = clean_summary.replace("\n", "<br>")  # preserve line breaks
    st.markdown(f"<div class='plan-card'>{html_summary}</div>", unsafe_allow_html=True)


    # Action buttons
    st.markdown("---")
    col1, col2, col3 = st.columns(3)

    with col1:
        if st.button("🆕 New Plan", use_container_width=True):
            st.session_state["result"] = None
            st.session_state["current_goal_id"] = None
            st.session_state["decomposition"] = None
            st.rerun()

    with col2:
        plan_text = f"""Goal: {result.goal}

Your Daily Practices:
{chr(10).join(f'{i}. {act}' for i, act in enumerate(result.suggested_activities, 1))}

About This Plan:
{clean_summary}

---
Created with Corporate Mindfulness Mentor
"""
        st.download_button(
            label="📥 Download",
            data=plan_text,
            file_name=f"{result.goal[:30].replace(' ', '_')}.txt",
            mime="text/plain",
            use_container_width=True,
        )

    with col3:
        if current_id and current_id in st.session_state["saved_plans"]:
            plan_data = st.session_state["saved_plans"][current_id]
            md_content = export_plan_markdown(plan_data)
            st.download_button(
                label="📄 Export MD",
                data=md_content,
                file_name=f"{result.goal[:30].replace(' ', '_')}.md",
                mime="text/markdown",
                use_container_width=True,
            )



# ──────────────────────────────────────────────────────────────────────────────
# 👤 Profile Personalization (runs after you have a base plan)
# ──────────────────────────────────────────────────────────────────────────────
st.markdown("---")
st.markdown("## 👤 Profile Personalization")

with st.form("profile_form", clear_on_submit=False):
    colA, colB = st.columns(2)
    with colA:
        work_schedule = st.text_input("Work schedule", placeholder="Mon–Fri, 9–6; commute 30m")
        typical_stress = st.slider("Typical stress (0–10)", 0, 10, 5)
    with colB:
        prefs = st.text_input("Preferences (comma-separated)", placeholder="short sessions, breathing")
        cons = st.text_input("Constraints (comma-separated)", placeholder="no audio, shared desk")

    personalize_submit = st.form_submit_button("🎯 Personalize my plan")

if personalize_submit:
    if st.session_state.get("result") is None:
        st.info("Generate a goal plan first, then personalize it.")
    else:
        from graph.schemas import Goal, UserProfile
        g = Goal(
            goal_name=st.session_state["result"].goal,
            duration_type=st.session_state.get("last_input",{}).get("duration_type","weekly"),
            description=st.session_state.get("last_input",{}).get("description","")
        )
        profile = UserProfile(
            work_schedule=work_schedule.strip() or "Mon–Fri",
            typical_stress_level=int(typical_stress),
            preferences=[p.strip() for p in (prefs or "").split(",") if p.strip()],
            constraints=[c.strip() for c in (cons or "").split(",") if c.strip()],
        )
        try:
            with st.spinner("Tailoring your plan to your schedule..."):
                p = run_personalized_goal(g, profile)

            st.success("✅ Personalized plan created")
            st.markdown("### 🎯 Personalized Activities")
            for i, a in enumerate(p.activities, 1):
                st.markdown(f"{i}. {a}")
            st.markdown("### 📝 Why this fits you")
            st.info(p.summary)
            st.session_state["personalized"] = p
        except Exception as e:
            st.error(f"Could not personalize plan: {e}")


# ──────────────────────────────────────────────────────────────────────────────
# ⚙️ Workload-Based Adaptation (same section, uses today’s load)
# ──────────────────────────────────────────────────────────────────────────────
st.markdown("## ⚙️ Workload-Based Adaptation (Today)")

with st.form("workload_form", clear_on_submit=False):
    col1, col2, col3 = st.columns(3)
    with col1:
        w_date = st.date_input("Date")
        meetings = st.number_input("Meetings (count)", min_value=0, step=1, value=4)
    with col2:
        busy_hours = st.number_input("Busy hours (today)", min_value=0.0, step=0.5, value=4.0)
        fatigue = st.selectbox("Fatigue", ["", "low", "medium", "high"], index=2)
    with col3:
        blockers = st.text_input("Blockers (comma-separated)", placeholder="oncall, release")
    adapt_submit = st.form_submit_button("🔧 Adapt today’s plan")

if adapt_submit:
    base = st.session_state.get("personalized") or st.session_state.get("result")
    base_acts = []
    if base:
        # both PersonalizedPlanResponse and PlanResponse have activity lists
        base_acts = getattr(base, "activities", None) or getattr(base, "suggested_activities", None) or []

    if not base_acts:
        st.info("Create or personalize a plan first, then adapt it.")
    else:
        from graph.schemas import Goal, WorkloadReport
        g = Goal(
            goal_name= (getattr(base, "goal", None) or st.session_state["result"].goal),
            duration_type=st.session_state.get("last_input",{}).get("duration_type","weekly"),
            description=st.session_state.get("last_input",{}).get("description","")
        )
        wl = WorkloadReport(
            date=w_date.isoformat(),
            meetings=int(meetings),
            busy_hours=float(busy_hours),
            fatigue=(fatigue or None),
            blockers=[b.strip() for b in (blockers or "").split(",") if b.strip()]
        )
        try:
            from graph.graph import run_workload_adaptation
            with st.spinner("Right-sizing today’s steps..."):
                adapted = run_workload_adaptation(g, base_acts, wl)

            st.success("✅ Adapted plan for today")
            st.markdown("### 📋 Today’s Micro-Plan")
            for i, a in enumerate(adapted.day_plan, 1):
                st.markdown(f"{i}. {a}")
            st.markdown("### 💡 Rationale")
            st.caption(adapted.rationale)
        except Exception as e:
            st.error(f"Could not adapt today’s plan: {e}")


# ──────────────────────────────────────────────────────────────────────────────
# 🧘 Mindfulness Break Notifications (User Story)
# ──────────────────────────────────────────────────────────────────────────────

st.markdown("---")
st.markdown("## 🕒 Mindfulness Break Notifications")

# Manual trigger
if st.button("🌼 Take a Mindful Break", key="manual_break"):
    run_break_workflow()  # don’t show the return text
    st.balloons()
    st.session_state["last_reminder_time"] = datetime.now()
    st.info("✅ Mindful break recorded successfully.")

if st.button("🤖 AI-Powered Mindful Break"):
    llm_output = run_llm_break_workflow()
    st.markdown("### 🌼 AI-Powered Mindful Suggestion")
    st.info(llm_output["message"])
    st.success(llm_output["reflection"])
    st.caption(f"💡 {llm_output['recommendation']}")




# Auto reminder controls
enable_auto_breaks = st.checkbox("Enable automatic reminders", value=True, key="auto_reminder_box")
interval = st.slider("Remind me every (minutes)", 15, 120, 60, 15, key="interval_main_slider")
play_sound = st.checkbox("🔔 Sound alert", value=True, key="sound_alert_box")

# Run auto reminders
if enable_auto_breaks:
    auto_mindfulness_reminder(interval_minutes=interval, enable_sound=play_sound)

# Show latest break info
if os.path.exists("data/break_log.json"):
    try:
        with open("data/break_log.json", "r") as f:
            logs = json.load(f)
        if logs:
            latest = logs[-1]
            st.markdown(
                f"<p style='font-size:16px;'><b>🕒 Last Break:</b> {latest['scheduled_time']} — {latest['message']}</p>",
                unsafe_allow_html=True,
            )
        else:
            st.info("No recent break logs found.")
    except Exception as e:
        st.error(f"Error reading break log: {e}")

# Show today's break chart
def show_break_chart():
    if not os.path.exists("data/break_log.json"):
        st.info("No breaks logged yet.")
        return
    logs = json.load(open("data/break_log.json"))
    df = pd.DataFrame(logs)
    df["time"] = pd.to_datetime(df["scheduled_time"])
    today = df[df["time"].dt.date == datetime.today().date()]
    if today.empty:
        st.info("No breaks logged today yet.")
        return
    st.markdown("### 🧘 Today's Breaks")
    chart = (
        alt.Chart(today)
        .mark_bar()
        .encode(x="time:T", y="count()", tooltip=["message"])
        .properties(height=200)
    )
    st.altair_chart(chart, use_container_width=True)

show_break_chart()


# ──────────────────────────────────────────────────────────────────────────────
# Footer
# ──────────────────────────────────────────────────────────────────────────────
st.markdown("---")
st.markdown(
    """
<div style='text-align: center; color: #666; padding: 24px 0;'>
    <p style='font-size: 16px; margin-bottom: 8px;'>
        💡 <strong>Remember:</strong> Small, consistent steps lead to lasting change.
    </p>
    <p style='font-size: 13px; color: #999;'>
        Your plans are saved in this session. Download them to keep permanently.
    </p>
</div>
""",
    unsafe_allow_html=True,
)





#----break-----

# ──────────────────────────────────────────────────────────────────────────────
# 🌅 Morning Wellness Check-In (User Story)
# ──────────────────────────────────────────────────────────────────────────────
st.markdown("---")
st.markdown("## 🌅 Morning Wellness Check-In")

with st.form("checkin_form", clear_on_submit=False):
    col1, col2 = st.columns(2)
    with col1:
        mood = st.selectbox("Mood", ["", "calm", "neutral", "anxious", "frustrated"])
        energy = st.selectbox("Energy", ["", "low", "medium", "high"])
    with col2:
        sleep = st.selectbox("Sleep quality", ["", "poor", "ok", "great"])
        workload = st.selectbox("Workload", ["", "light", "normal", "heavy"])
    notes = st.text_area("Notes (optional)")
    do_checkin = st.form_submit_button("Adjust my plan for today")

if do_checkin:
    ck = CheckIn(
        mood=mood or None,
        sleep_quality=sleep or None,
        energy=energy or None,
        workload=workload or None,
        notes=notes or None,
    )
    adj = run_morning_checkin(ck)

    # Optional: save to disk if you decide to re-enable later
    # from services.checkin_storage import save_checkin
    # save_checkin(ck.model_dump(), adj.model_dump())

    if adj.summary:
        st.success(adj.summary)

    if adj.focus_for_today:
        st.markdown("**Focus for today**")
        for a in adj.focus_for_today:
            st.write(f"- {a}")

    if adj.risk_flags:
        st.caption("Flags: " + ", ".join(adj.risk_flags))


# ──────────────────────────────────────────────────────────────────────────────
# 🌬 Guided Meditations, Breathing & Body Scans (User Story 4)
# ──────────────────────────────────────────────────────────────────────────────
st.markdown("---")
st.markdown("## 🌬 Guided Meditations & Breathing Exercises")




init_session()

st.markdown("### 🧭 Personalize Your Session")
user_goal = st.text_input("Describe your current state or need:", "")
stress_level = st.slider("Stress Level", 0, 10, 0)

# 🚀 Ensure user enters a goal before generating techniques
if user_goal.strip() == "":
    st.warning("Please describe your current state or need before continuing.")
else:
    if st.button("💡 Get AI-Recommended Techniques"):
        with st.spinner("Analyzing your needs..."):
            result = run_mentor_cycle(
                user_goal=user_goal,
                stress_level=stress_level,
                profile={"context": "corporate", "session_type": "guided_practice"},
                history=st.session_state.get("session_history", []),
            )

            # 🧩 Ensure JSON is parsed
            if isinstance(result, str):
                import json
                try:
                    result = json.loads(result)
                except Exception as e:
                    st.error(f"⚠️ Could not parse AI response: {e}")
                    st.stop()

            # ✅ Store and display
            st.session_state["techniques"] = result.get("techniques", [])
            st.session_state["summary"] = result.get("summary", "Stay mindful and consistent!")

            if st.session_state["techniques"]:
                st.success("✨ Here are your personalized AI mindfulness techniques:")
                for technique in st.session_state["techniques"]:
                    st.markdown(f"### 🧘 {technique['title']} · _{technique['duration_min']} min_")
                    st.write(technique["description"])
                    for step in technique["steps"]:
                        st.markdown(f"- {step}")
                st.markdown(f"---\n**Reflection:** {st.session_state['summary']}")
            else:
                st.warning("⚠️ No AI-generated techniques received. Try again or check your API key.")




if "recommended_ids" in st.session_state and st.session_state["recommended_ids"]:
    st.markdown("### ✨ AI Recommendations")
    if st.session_state.get("summary"):
        st.caption("AI reasoning: " + st.session_state["summary"])

    for rid in st.session_state["recommended_ids"]:
        item = find_item(lib, rid)
        if not item:
            continue
        with st.container(border=True):
            st.markdown(f"**{item.title}** · _{item.duration_min} min_")
            st.write(item.description)
            st.caption(", ".join(item.tags))
            if st.button(f"▶ Start {item.title}", key=f"start_{rid}"):
                start_session(rid)
                st.rerun()

# Active session view
s = get_state()
if s["running"]:
    item = find_item(lib, s["active_item_id"])
    if item:
        step_idx = s["step_index"]
        step_idx = min(step_idx, len(item.steps) - 1)
        st.progress(step_idx / len(item.steps))
        st.markdown(f"**Step {step_idx + 1} of {len(item.steps)}**")
        st.info(item.steps[step_idx])
        c1, c2 = st.columns(2)
        with c1:
            if st.button("⏭ Next"):
                next_step(); st.rerun()
        with c2:
            if st.button("⏹ End"):
                stop_session(); st.success("Session completed!")
else:
    st.caption("🧘 Select or start a technique to begin.")




